import { USER_ROLES, MODULES, PERMISSIONS } from '../../shared/schema.js';

// Define role-based permissions for each module
const rolePermissions = {
  [USER_ROLES.SUPER_USER]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.ORDERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.MANUFACTURING]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.DISPATCHES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.SALES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.ACCOUNTS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.INVENTORY]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.CUSTOMERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.SUPPLIERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.PURCHASES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.SETTINGS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER]
  },
  [USER_ROLES.UNIT_HEAD]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.ORDERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.MANUFACTURING]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.DISPATCHES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.SALES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.ACCOUNTS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.INVENTORY]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.CUSTOMERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.SUPPLIERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.PURCHASES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER]
  },
  [USER_ROLES.PRODUCTION]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.ORDERS]: [PERMISSIONS.VIEW],
    [MODULES.MANUFACTURING]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.INVENTORY]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT]
  },
  [USER_ROLES.PACKING]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.ORDERS]: [PERMISSIONS.VIEW],
    [MODULES.MANUFACTURING]: [PERMISSIONS.VIEW],
    [MODULES.DISPATCHES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.INVENTORY]: [PERMISSIONS.VIEW]
  },
  [USER_ROLES.DISPATCH]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.ORDERS]: [PERMISSIONS.VIEW],
    [MODULES.DISPATCHES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.INVENTORY]: [PERMISSIONS.VIEW]
  },
  [USER_ROLES.ACCOUNTS]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.ORDERS]: [PERMISSIONS.VIEW],
    [MODULES.SALES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.ACCOUNTS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.ALTER],
    [MODULES.CUSTOMERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.SUPPLIERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.PURCHASES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT]
  }
};

export const hasPermission = (userRole, module, permission) => {
  const modulePermissions = rolePermissions[userRole]?.[module];
  return modulePermissions?.includes(permission) || false;
};

export const getUserModules = (userRole) => {
  return Object.keys(rolePermissions[userRole] || {});
};

export const getModulePermissions = (userRole, module) => {
  return rolePermissions[userRole]?.[module] || [];
};

export const checkModuleAccess = (userRole, module) => {
  return rolePermissions[userRole]?.[module]?.length > 0 || false;
};
